name: test

on:
  push:
  pull_request:
  schedule:
    - cron: "30 14 * * *"

jobs:
  test-ruby-versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['head', '3.2', '3.1', '3.0']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rake test

  test-rbs-versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rbs: ['latest', '3.0', '2.7.0']
    env:
      GEMFILE_RBS_VERSION: ${{matrix.rbs}}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rake test

  test-prism-versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        prism: ['0.17.1']
    env:
      GEMFILE_PRISM_VERSION: ${{matrix.prism}}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rake test
